In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [3]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [6]:
one_hot("amazing restaurant", 30) 

[14, 25]

In [7]:
vocab_size = 30 
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]

In [8]:
encoded_reviews

[[3, 18],
 [14, 25],
 [27, 15],
 [29, 15, 6],
 [6, 18, 22],
 [14, 18],
 [2, 18, 15],
 [29, 3],
 [29, 14],
 [24, 16]]

In [10]:
max_length = 4 
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding="post") 

In [11]:
padded_reviews

array([[ 3, 18,  0,  0],
       [14, 25,  0,  0],
       [27, 15,  0,  0],
       [29, 15,  6,  0],
       [ 6, 18, 22,  0],
       [14, 18,  0,  0],
       [ 2, 18, 15,  0],
       [29,  3,  0,  0],
       [29, 14,  0,  0],
       [24, 16,  0,  0]], dtype=int32)

In [16]:
embeded_vector_size = 5 
model = Sequential() 
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, name = "embedding"))

In [17]:
model.add(Flatten()) 

In [18]:
model.add(Dense(1, activation="sigmoid"))

In [19]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [20]:
X = padded_reviews
y = sentiment

In [21]:
model.fit(X, y, epochs=50) 

Epoch 1/50
1/1 [==============================] - 0s 391ms/step - loss: 0.6985 - accuracy: 0.4000
Epoch 2/50
1/1 [==============================] - 0s 3ms/step - loss: 0.6975 - accuracy: 0.4000
Epoch 3/50
1/1 [==============================] - 0s 3ms/step - loss: 0.6964 - accuracy: 0.4000
Epoch 4/50
1/1 [==============================] - 0s 2ms/step - loss: 0.6954 - accuracy: 0.4000
Epoch 5/50
1/1 [==============================] - 0s 3ms/step - loss: 0.6944 - accuracy: 0.4000
Epoch 6/50
1/1 [==============================] - 0s 2ms/step - loss: 0.6934 - accuracy: 0.5000
Epoch 7/50
1/1 [==============================] - 0s 2ms/step - loss: 0.6924 - accuracy: 0.6000
Epoch 8/50
1/1 [==============================] - 0s 2ms/step - loss: 0.6914 - accuracy: 0.6000
Epoch 9/50
1/1 [==============================] - 0s 2ms/step - loss: 0.6903 - accuracy: 0.7000
Epoch 10/50
1/1 [==============================] - 0s 2ms/step - loss: 0.6893 - accuracy: 0.7000
Epoch 11/50
1/1 [====================

In [24]:
model.predict(["awful food"])

ValueError: in user code:

    File "/Users/azamsharp/Desktop/sample_project/env/lib/python3.10/site-packages/keras/engine/training.py", line 2041, in predict_function  *
        return step_function(self, iterator)
    File "/Users/azamsharp/Desktop/sample_project/env/lib/python3.10/site-packages/keras/engine/training.py", line 2027, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/azamsharp/Desktop/sample_project/env/lib/python3.10/site-packages/keras/engine/training.py", line 2015, in run_step  **
        outputs = model.predict_step(data)
    File "/Users/azamsharp/Desktop/sample_project/env/lib/python3.10/site-packages/keras/engine/training.py", line 1983, in predict_step
        return self(x, training=False)
    File "/Users/azamsharp/Desktop/sample_project/env/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/Users/azamsharp/Desktop/sample_project/env/lib/python3.10/site-packages/keras/engine/input_spec.py", line 277, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer "sequential_4" "                 f"(type Sequential).
    
    Input 0 of layer "dense" is incompatible with the layer: expected axis -1 of input shape to have value 20, but received input with shape (None, 5)
    
    Call arguments received by layer "sequential_4" "                 f"(type Sequential):
      • inputs=tf.Tensor(shape=(None,), dtype=string)
      • training=False
      • mask=None


In [25]:
padding_reviews

array([[ 3, 18,  0,  0],
       [14, 25,  0,  0],
       [27, 15,  0,  0],
       [29, 15,  6,  0],
       [ 6, 18, 22,  0],
       [14, 18,  0,  0],
       [ 2, 18, 15,  0],
       [29,  3,  0,  0],
       [29, 14,  0,  0],
       [24, 16,  0,  0]], dtype=int32)

In [29]:
prediction = model.predict([14, 25,  0,  0])

1/1 [==============================] - 0s 24ms/step


In [30]:
prediction = (prediction > 0.5).astype("int32")

print(prediction)

[[1]]


In [45]:
bad_review = "good food"
encoded_review = one_hot(bad_review, vocab_size) 
padded_reviews = pad_sequences([encoded_review], maxlen=max_length, padding="post") 

In [46]:
model.predict([padded_reviews])

1/1 [==============================] - 0s 13ms/step


array([[0.4942749]], dtype=float32)